### ISSUE TITLE
Bootstrap failed to complete   

### ISSUE THREAD

**Issue by pdas-cp4i** [rcarrata/ocp4-aws-upi-cf#1]
@rcarrata

 OCP v 4.8.28

I've followed all the steps. Bootstrap and master nodes are running. But all 3 NLB's failing health check.
openshift-install wait-for bootstrap-complete throwing following error.

Any thoughts?

ERROR Attempted to gather ClusterOperator status after wait failure: listing ClusterOperator objects: Get "https://api.myupicluster.demos-ipath.com:6443/apis/config.openshift.io/v1/clusteroperators": dial tcp 3.132.145.28:6443: connect: connection refused 
INFO Use the following commands to gather logs from the cluster 
INFO openshift-install gather bootstrap --help    
ERROR Bootstrap failed to complete: Get "https://api.myupicluster.demos-ipath.com:6443/version?timeout=32s": dial tcp 18.189.104.213:6443: connect: connection refused 
ERROR Failed waiting for Kubernetes API. This error usually happens when there is a problem on the bootstrap host that prevents creating a temporary control plane. 
FATAL Bootstrap failed to complete                 

Thanks,
Purush

**Comment by rcarrata** [comment]
hi there! 

Seems to me, that the Bootstrap is not able to reach the OCP/k8s apiserver in 6443. 

I suggest two possible root cause diagnostics:

1- Check the Security Groups in order to know if there are connectivity allowed between bootstrap and masters (there are specific SGs for each).

2- Check in the masters (you can access using the oc debug or directly ssh-ing to the node with the pem used in the install-config) and check the journalctl in order to verify that the kubeapi server is up && running, and if there are other errors.

Thanks for commenting!
